# Generated by Django 5.0.4 on 2024-05-04 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images', verbose_name='Imagen'),
        ),
    ]
