# Generated by Django 5.0.4 on 2024-05-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0004_carritodetalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoDetalle',
        ),
    ]
